version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: reza
      MONGO_INITDB_ROOT_PASSWORD: reza
      MONGO_INITDB_DATABASE: admin